### ISSUE TITLE
Add alternative link

### ISSUE THREAD

**Issue by Lancetnik** [adriangb/di#99]
Hello there! You made a really awesome project!

As you were, I was inspired by **FastAPI** Dependency Injection System too. So I created a more lightweight package than yours [**Fast Depends**](https://github.com/Lancetnik/FastDepends). In the documentation, I added a link to your project as a more complex and powerful alternative. I think people found your project also can be interested in **Fast Depends**, so can you add a link to it too? It's not a real concurrent package and I have no plans to grow its functionality in the future. It's just a part of **FastAPI** can be used everywhere.

**Comment by morning-sunn** [comment]
@Lancetnik like that you decoupled it from http, is always a good idea. That's even why I didn't really bother to use the Depends from FastAPI, because web-frameworks can be swapped at any point, and it shouldn't be a pain to do so. I just dislike it, it's a taste thing that I like injector and exploring this, although it didn't have any progress for the past 3 months

**Comment by adriangb** [comment]
Sorry that I never got around to replying. I've been too busy with Pydantic v2. Happy to add a link to your project if you want to make a PR, but maybe there should be a `## Similar projects` section or something, not just 1 link.

**Comment by Lancetnik** [comment]
Okay, will try to make smth tomorrow.

Anyway, **FastDepends** is not the similar project: it is just validates function inputs by pydantic and solve Depends functions, more... But it is enough to build more complex tools on top of it: like [Propan](https://lancernik.github.io/Propan).

May be you can try use it underground too. I am have no plans to expand functionality, but working on rewrite it to Rust to use pydantic_core native way. At now it works with PydanticV1 and PydanticV2 as well.

**Comment by adriangb** [comment]
I'm not sure what you mean. You won't be able to call `pydantic-core` from Rust, there is no ABI for that.

**Comment by Lancetnik** [comment]
> I'm not sure what you mean. You won't be able to call `pydantic-core` from Rust, there is no ABI for that.

It can be added if it is required

**Comment by Lancetnik** [comment]
@adriangb next week I will fork *pydantic-core* and try to build it to separated cargo package to provide It functionality as a Rust package too.
It can be extremely helpful for the community, cuz allows to build a new pydantic-based Rust tools on top of it, do you think the same?

**Comment by adriangb** [comment]
Not really. But it sounds like you have a vision for this, don’t let me stop you!
